name: EditorConfig checks

on:
  pull_request:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check files for EditorConfig compliance
        uses: editorconfig-checker/action-editorconfig-checker@fc46e05012a3cb292d4b1e6306f598d74ebd5458 # untagged main
        with:
          version: 2.7.0
