name: EditorConfig checks

on:
  pull_request:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check files for EditorConfig compliance
        uses: editorconfig-checker/action-editorconfig-checker@525002b6966edac05c6a52a25409dda3df4af661 # untagged main
        with:
          version: 2.7.0
