name: EditorConfig checks

on:
  pull_request:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check files for EditorConfig compliance
        uses: editorconfig-checker/action-editorconfig-checker@b8ff0d8c9ff9f36a2e28674fea1f3dea1aa97cf0 # untagged main
        with:
          version: 2.7.0
